version: "3.7"
services:

  #############################################################################################
  ###                           Document Utils api                                          ###
  #############################################################################################
  document-utils-api:
    build:
      context: ./src/document-utils-api
      args:
        - MVN_PROFILE=openshift
        - SKIP_TESTS=true
    ports:
      - "8080:8080"
    environment:
      - DOCMERGE_AEM_ENDPOINT=${DOCMERGE_AEM_ENDPOINT}
      - DOCMERGE_AEM_USER=${DOCMERGE_AEM_USER}
      - DOCMERGE_AEM_PASSWORD=${DOCMERGE_AEM_PASSWORD}
      - ENABLE_SWAGGER_UI=true
    networks:
      - doc-utils

networks:
  doc-utils:
    driver: "bridge"
