name: Docker Build and Push - WEB

on:
  workflow_dispatch:
    branches: [main]
  push:
    branches: [main, git-docker]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Build API
      - name: Build, tag, and push image to Amazon ECR
        id: build-web
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t teamapple/document-utils:latest ./src/document-utils-api
          docker push teamapple/document-utils:latest
