name: Docker Build and Push - WEB

on: 
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.8
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
          
      # Build API
      - name: Build, tag, and push latest and tag image to repository
        id: build-web
        run: |

          docker-compose build document-utils-api 
          docker tag jag-document-utils_document-utils-api:latest teamapple/document-utils-api:latest
          docker push teamapplentt/document-utils-api:latest
          docker tag jag-document-utils_document-utils-api:latest teamapple/document-utils-api:${​​​​​{​​​​​ github.event.release.tag_name }​​​​​}​​​​​
          docker push teamapplentt/document-utils-api:${​​​​​{​​​​​ github.event.release.tag_name }​​​​​}​​​​​
