name: Docker Build and Push - WEB

on:
  workflow_dispatch:
    branches: [main]
  push:
    branches: [main, git-docker]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Build API
      - name: Build, tag, and push image to Docker Hub
        id: build-web
        run: |
          docker-compose build document-utils-api 
          docker tag document-utils-api:latest teamapple/document-utils-api:latest
          docker push teamapple/document-utils:latest
